/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'page-index': RouteRecordInfo<'page-index', '/', Record<never, never>, Record<never, never>>,
    'page-certificate-one-handover': RouteRecordInfo<'page-certificate-one-handover', '/certificate/reservationOneHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-two-handover': RouteRecordInfo<'page-certificate-two-handover', '/certificate/reservationTwoHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-revocation': RouteRecordInfo<'page-certificate-revocation', '/certificate/revocation', Record<never, never>, Record<never, never>>,
    'page-certificate-site-handover': RouteRecordInfo<'page-certificate-site-handover', '/certificate/siteHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-transfer-in': RouteRecordInfo<'page-certificate-transfer-in', '/certificate/transferIn', Record<never, never>, Record<never, never>>,
    'page-certificate-transfer-out': RouteRecordInfo<'page-certificate-transfer-out', '/certificate/transferOut', Record<never, never>, Record<never, never>>,
    'page-certificate-turn-in': RouteRecordInfo<'page-certificate-turn-in', '/certificate/turnIn', Record<never, never>, Record<never, never>>,
    'page-certificate-use': RouteRecordInfo<'page-certificate-use', '/certificate/use', Record<never, never>, Record<never, never>>,
    'page-demo': RouteRecordInfo<'page-demo', '/demo', Record<never, never>, Record<never, never>>,
    'page-important-outbound': RouteRecordInfo<'page-important-outbound', '/important/outbound', Record<never, never>, Record<never, never>>,
    'page-important-putBack': RouteRecordInfo<'page-important-putBack', '/important/putBack', Record<never, never>, Record<never, never>>,
    'page-reservation-one-handover': RouteRecordInfo<'page-reservation-one-handover', '/important/reservationOneHandover', Record<never, never>, Record<never, never>>,
    'page-reservation-two-handover': RouteRecordInfo<'page-reservation-two-handover', '/important/reservationTwoHandover', Record<never, never>, Record<never, never>>,
    'page-site-handover': RouteRecordInfo<'page-site-handover', '/important/siteHandover', Record<never, never>, Record<never, never>>,
    'page-important-takeOut': RouteRecordInfo<'page-important-takeOut', '/important/takeOut', Record<never, never>, Record<never, never>>,
    'page-important-transfer-in': RouteRecordInfo<'page-important-transfer-in', '/important/transferIn', Record<never, never>, Record<never, never>>,
    'page-important-transfer-out': RouteRecordInfo<'page-important-transfer-out', '/important/transferOut', Record<never, never>, Record<never, never>>,
    'page-important-turn-in': RouteRecordInfo<'page-important-turn-in', '/important/turnIn', Record<never, never>, Record<never, never>>,
    'page-important-warehouse': RouteRecordInfo<'page-important-warehouse', '/important/warehouse', Record<never, never>, Record<never, never>>,
    'page-register': RouteRecordInfo<'page-register', '/register', Record<never, never>, Record<never, never>>,
    'page-storage-one-handover': RouteRecordInfo<'page-storage-one-handover', '/storage/reservationOneHandover', Record<never, never>, Record<never, never>>,
    'page-storage-two-handover': RouteRecordInfo<'page-storage-two-handover', '/storage/reservationTwoHandover', Record<never, never>, Record<never, never>>,
    'page-storage-site-handover': RouteRecordInfo<'page-storage-site-handover', '/storage/siteHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-receiver-one-handover': RouteRecordInfo<'page-certificate-receiver-one-handover', '/todo/certificate/receiverOneHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-receiver-two-handover': RouteRecordInfo<'page-certificate-receiver-two-handover', '/todo/certificate/receiverTwoHandover', Record<never, never>, Record<never, never>>,
    'page-certificate-supervisor-two-handover': RouteRecordInfo<'page-certificate-supervisor-two-handover', '/todo/certificate/supervisorTwoHandover', Record<never, never>, Record<never, never>>,
    'page-important-receiver-one-handover': RouteRecordInfo<'page-important-receiver-one-handover', '/todo/Important/receiverOneHandover', Record<never, never>, Record<never, never>>,
    'page-important-receiver-two-handover': RouteRecordInfo<'page-important-receiver-two-handover', '/todo/Important/receiverTwoHandover', Record<never, never>, Record<never, never>>,
    'page-important-supervisor-two-handover': RouteRecordInfo<'page-important-supervisor-two-handover', '/todo/Important/supervisorTwoHandover', Record<never, never>, Record<never, never>>,
    'page-todo-list': RouteRecordInfo<'page-todo-list', '/todo/list', Record<never, never>, Record<never, never>>,
    'page-storage-receiver-one-handover': RouteRecordInfo<'page-storage-receiver-one-handover', '/todo/storage/receiverOneHandover', Record<never, never>, Record<never, never>>,
    'page-storage-receiver-two-handover': RouteRecordInfo<'page-storage-receiver-two-handover', '/todo/storage/receiverTwoHandover', Record<never, never>, Record<never, never>>,
    'page-storage-supervisor-two-handover': RouteRecordInfo<'page-storage-supervisor-two-handover', '/todo/storage/supervisorTwoHandover', Record<never, never>, Record<never, never>>,
  }
}
