/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'page-index': RouteRecordInfo<'page-index', '/', Record<never, never>, Record<never, never>>,
    'page-reservation-one-handover': RouteRecordInfo<'page-reservation-one-handover', '/certificate/reservationOneHandover/inde', Record<never, never>, Record<never, never>>,
    'page-reservation-two-handover': RouteRecordInfo<'page-reservation-two-handover', '/certificate/reservationTwoHandover', Record<never, never>, Record<never, never>>,
    'page-demo': RouteRecordInfo<'page-demo', '/demo', Record<never, never>, Record<never, never>>,
    'page-important-outbound': RouteRecordInfo<'page-important-outbound', '/important/outbound', Record<never, never>, Record<never, never>>,
    'page-important-putBack': RouteRecordInfo<'page-important-putBack', '/important/putBack', Record<never, never>, Record<never, never>>,
    'page-reservation-one-handover': RouteRecordInfo<'page-reservation-one-handover', '/important/reservationOneHandover', Record<never, never>, Record<never, never>>,
    'page-reservation-two-handover': RouteRecordInfo<'page-reservation-two-handover', '/important/reservationTwoHandover', Record<never, never>, Record<never, never>>,
    'page-site-handover': RouteRecordInfo<'page-site-handover', '/important/siteHandover', Record<never, never>, Record<never, never>>,
    'page-important-takeOut': RouteRecordInfo<'page-important-takeOut', '/important/takeOut', Record<never, never>, Record<never, never>>,
    'page-important-warehouse': RouteRecordInfo<'page-important-warehouse', '/important/warehouse', Record<never, never>, Record<never, never>>,
    'page-todo-list': RouteRecordInfo<'page-todo-list', '/todo/list', Record<never, never>, Record<never, never>>,
    'page-receiver-one-handover': RouteRecordInfo<'page-receiver-one-handover', '/todo/receiverOneHandover', Record<never, never>, Record<never, never>>,
    'page-receiver-two-handover': RouteRecordInfo<'page-receiver-two-handover', '/todo/receiverTwoHandover', Record<never, never>, Record<never, never>>,
    'page-supervisor-two-handover': RouteRecordInfo<'page-supervisor-two-handover', '/todo/supervisorTwoHandover', Record<never, never>, Record<never, never>>,
  }
}
